name: test(main)

# Define the trigger for this workflow (runs on push to the develop branch)
on:
  workflow_dispatch:
    

# Define the jobs to run in this workflow
jobs:
  build:
  
    # Use a self-hosted runner  
    runs-on: ubuntu-latest
    
    # Define permissions for the job    
    permissions:
      contents: read        
      id-token: write
      checks: write
      
    # Steps to be executed within the job
    steps:
    
    # Step 1: Checkout code from the repository
    - name: 'Checkout code'
      uses: 'actions/checkout@v2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
